### ISSUE TITLE
Ошибка в скомпиленом коде

### ISSUE THREAD

**Issue by Nitive** [rispa-io/rispa-webpack#5]
Выполняем `ris webpack build`.
Запускаем js файл в браузере, получаем
`ReferenceError: Can't find variable: webpackJsonp`

**Comment by Laiff** [comment]
Там собирается несколько бандлов, и вероятно бандл с начальным кодом для старта приложения еще не загружен. 
При установке которого бандла происходит ошибка?

@wuzyk посмотри тоже

**Comment by wuzyk** [comment]
Есть подозрение, что проблема в следующем: когда мы хотя бы раз запускали сервер или сборку, создается папка build в которой сохраняется файлик stats.json, который использует universal-webpack для серверного рендеринга. Когда мы запускаем сервер второй раз, может получится так, что сервер скомпилится быстрее клиента и universal-webpack считает старый stats.json. 
Решение: удалять папку build перед каждый запуском сервера

**Comment by Fyzu** [comment]
Сбилдил проект с `@rispa/client`, подключил` bootstrap.js` и бандл, запуск прошел отлично.

![image](https://user-images.githubusercontent.com/6418302/27272400-9983d8d6-54d2-11e7-8fee-c05d04f1eddb.png)

**Comment by Nitive** [comment]
Я тестил таким образом: создал index.html и подключил в нём скрипт

**Comment by Nitive** [comment]
Но забыл подключить bootstrap.js
